=== IsyFact/isy-benutzerverwaltung/isy-benutzerverwaltung-gui-tomahawk/src/main/resources/resources/sicherheit/RollenRechteSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns:tns="http://www.example.org/RollenRechteSchema"
        xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.org/RollenRechteSchema"
        elementFormDefault="qualified">

    <complexType name="Rolle">
        <sequence>
            <element name="rechtId" type="tns:RechtId" minOccurs="0" maxOccurs="unbounded"/>
        </sequence>
        <attribute name="RolleId" type="string" use="required"/>
    </complexType>

    <complexType name="Recht">
        <sequence>
            <element name="rechtId" type="tns:RechtId" minOccurs="1" maxOccurs="1"/>
        </sequence>
    </complexType>

    <element name="Anwendung" type="tns:Anwendung"/>

    <complexType name="Anwendung">
        <sequence>
            <element name="rollen" type="tns:Rolle" minOccurs="1" maxOccurs="unbounded">
            </element>
            <element name="rechte" type="tns:Recht" minOccurs="0" maxOccurs="unbounded"/>
        </sequence>
        <attribute name="AnwendungsId" type="string" use="required"/>
    </complexType>

    <complexType name="RechtId">
        <attribute name="Id" type="string" use="required"/>
    </complexType>
</schema>

=== IsyFact/isy-benutzerverwaltung/isy-benutzerverwaltung-sicherheit/src/test/resources/resources/sicherheit/rollenrechte.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Anwendung xmlns:tns="http://www.example.org/RollenRechteSchema"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               AnwendungsId="restaurant"
               xsi:schemaLocation="http://www.example.org/RollenRechteSchema RollenRechteSchema.xsd">

    <tns:rollen RolleId="Administrator">
        <tns:rechtId Id="Benutzerverwaltung.Benutzer.Aendern"/>
        <tns:rechtId Id="Benutzerverwaltung.Benutzer.Aendern.Selbst"/>
    </tns:rollen>

    <tns:rollen RolleId="Rolle_A">
        <tns:rechtId Id="Recht_A"/>
    </tns:rollen>

    <tns:rollen RolleId="Rolle_B">
        <tns:rechtId Id="Recht_B"/>
    </tns:rollen>

    <tns:rechte>
        <tns:rechtId Id="Benutzerverwaltung.Benutzer.Lesen"/>
    </tns:rechte>
    <tns:rechte>
        <tns:rechtId Id="Benutzerverwaltung.Benutzer.Suchen"/>
    </tns:rechte>
    <tns:rechte>
        <tns:rechtId Id="Benutzerverwaltung.Benutzer.Aendern"/>
    </tns:rechte>
    <tns:rechte>
        <tns:rechtId Id="Benutzerverwaltung.Benutzer.Aendern.Selbst"/>
    </tns:rechte>
    <tns:rechte>
        <tns:rechtId Id="Benutzerverwaltung.Benutzer.Loeschen"/>
    </tns:rechte>

    <tns:rechte>
        <tns:rechtId Id="Recht_A"/>
    </tns:rechte>
    <tns:rechte>
        <tns:rechtId Id="Recht_B"/>
    </tns:rechte>

</tns:Anwendung>

=== IsyFact/isy-benutzerverwaltung/isy-benutzerverwaltung-gui-tomahawk/target/classes/resources/sicherheit/rollenrechte.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Diese Datei enth채lt alle Rechte, die in der Benutzerverwaltung definiert und gepr체ft werden.
Die Rollen sind als Beispiel zu verstehen, wie eine Anwendung die Rechte verteilen kann.
Der hier aufgef체hrte Inhalt kann als Startpunkt die rollenrechte.xml der Anwendung 체bertragen werden.
-->
<tns:Anwendung xmlns:tns="http://www.example.org/RollenRechteSchema"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               AnwendungsId="isy-benutzerverwaltung-gui-primefaces"
               xsi:schemaLocation="http://www.example.org/RollenRechteSchema RollenRechteSchema.xsd">

    <tns:rollen RolleId="Benutzer">
        <tns:rechtId Id="Benutzerverwaltung.Benutzer.Aendern.Selbst"/>
    </tns:rollen>
    <tns:rollen RolleId="Administrator">
        <tns:rechtId Id="Benutzerverwaltung.Benutzer.Anlegen"/>
        <tns:rechtId Id="Benutzerverwaltung.Benutzer.Suchen"/>
        <tns:rechtId Id="Benutzerverwaltung.Benutzer.Aendern"/>
        <tns:rechtId Id="Benutzerverwaltung.Benutzer.Loeschen"/>
        <tns:rechtId Id="Benutzerverwaltung.Benutzer.Aendern.Selbst"/>

        <tns:rechtId Id="Benutzerverwaltung.Rolle.Anlegen"/>
        <tns:rechtId Id="Benutzerverwaltung.Rolle.Suchen"/>
        <tns:rechtId Id="Benutzerverwaltung.Rolle.Aendern"/>
        <tns:rechtId Id="Benutzerverwaltung.Rolle.Loeschen"/>
    </tns:rollen>

    <!-- Benutzerverwaltung -->
    <tns:rechte>
        <tns:rechtId Id="Benutzerverwaltung.Benutzer.Anlegen"/>
    </tns:rechte>
    <tns:rechte>
        <tns:rechtId Id="Benutzerverwaltung.Benutzer.Suchen"/>
    </tns:rechte>
    <tns:rechte>
        <tns:rechtId Id="Benutzerverwaltung.Benutzer.Aendern"/>
    </tns:rechte>
    <tns:rechte>
        <tns:rechtId Id="Benutzerverwaltung.Benutzer.Loeschen"/>
    </tns:rechte>
    <tns:rechte>
        <tns:rechtId Id="Benutzerverwaltung.Benutzer.Aendern.Selbst"/>
    </tns:rechte>

    <!-- Rollenverwaltung -->
    <tns:rechte>
        <tns:rechtId Id="Benutzerverwaltung.Rolle.Anlegen"/>
    </tns:rechte>
    <tns:rechte>
        <tns:rechtId Id="Benutzerverwaltung.Rolle.Suchen"/>
    </tns:rechte>
    <tns:rechte>
        <tns:rechtId Id="Benutzerverwaltung.Rolle.Aendern"/>
    </tns:rechte>
    <tns:rechte>
        <tns:rechtId Id="Benutzerverwaltung.Rolle.Loeschen"/>
    </tns:rechte>

</tns:Anwendung>
